config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'

  post    :login,  to: 'sessions#create'
  delete  :logout, to: 'sessions#destroy'

  get :my_account, to: 'pages#my_account', path: 'mon-compte'
  get :finalize,   to: 'carts#finalize', path: 'finaliser-ma-commande'
  put :checkout,   to: 'carts#checkout', path: 'checkout-ma-commande'

  resources :users do
    resources :addresses, controller: 'users/addresses'
    resources :orders,    controller: 'users/orders'
  end

  resources :orders
  resources :products,  only: [:index, :show]
  resources :carts,     only: [:show, :create] do 
    resources :products, only: [:destroy]
  end

  resources :password_resets, only: [:new, :create, :edit, :update] do
  	collection do
  		get :success
  	end
  end

  namespace :admin do
    get :dashboard, to: 'admin#dashboard'
    resources :users
    resources :products
    resources :recipes
  end
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id                   :integer          not null, primary key
#  name                 :string
#  quantity             :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  picture_file_name    :string
#  picture_content_type :string
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#

class Recipe < ApplicationRecord
  # Associations
  has_many :recipezations, dependent: :destroy
  has_many :products, through: :recipezations
  validates :name, presence: true, uniqueness: true
  validates :quantity, presence: true

  has_attached_file :picture, styles: { svg: "900x500>", large: "520x520>", medium: "300x300>", small: "200x200>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/controllers/admin/recipes_controller.rb
module Admin
  class RecipesController < AdminController
    before_action :find_recipe, only: [:show, :edit, :update]

    def index
      @recipes = Recipe.all
    end

    def show
      @products = @recipe.products
    end

    def new
      @recipe = Recipe.new
    end

    def create
      @recipe = Recipe.new(recipe_params)
      if @recipe.save
        flash[:success] = 'Ingredient ajouté'
        redirect_to admin_recipes_path
      else
        flash.now[:danger] = 'Ingredient non ajouté'
        render :new
      end
    end

    def edit
    end

    def update
      if @recipe.update(recipe_params)
        flash[:success] = 'Ingredient modifié'
        redirect_to admin_recipes_path
      else
        flash.now[:danger] = 'Ingredient non modifié'
        render :edit
      end
    end

    private
    def recipe_params
      params.require(:recipe).permit(:name, :quantity, :picture)
    end

    def find_recipe
      @recipe = Recipe.find(params[:id])
    end
  end
end

app/views/admin/recipes/edit.html.erb
<div class='container'>
  <h1 class='text-center'>Edit <%= @recipe.name %></h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @recipe, url: admin_recipe_path(@recipe), method: :put, html: { multipart: true } do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %><br>

        <%= f.label :quantity %>
        <%= f.number_field :quantity, min: 0, class: 'form-control' %><br>

        <%= f.label :picture %>
        <%= f.file_field :picture, class: 'form-control' %><br>

        <%= f.submit 'Modifier', class: 'form-control' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/recipes/index.html.erb
<div class='container'>
  <h1 class='text-center'>Recipes#index</h1>

  <%= link_to 'Ajouter des recettes', new_admin_recipe_path %>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Picture</th>
        <th scope="col">Name</th>
        <th scope="col">Quantity</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @recipes.each do |recipe| %>
        <tr>
          <th scope="row"><%= recipe.id %></th>
          <td><%= image_tag recipe.picture.url(:thumb) %></td>
          <td><%= recipe.name %></td>
          <td><%= recipe.quantity %></td>
          <td><%= link_to 'Edit', edit_admin_recipe_path(recipe) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>  
</div>

app/views/admin/recipes/new.html.erb
<div class='container'>
  <h1 class='text-center'>Recipe#new</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @recipe, url: admin_recipes_path, html: { multipart: true } do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %><br>

        <%= f.label :quantity %>
        <%= f.number_field :quantity, min: 0, class: 'form-control' %><br>

        <%= f.label :picture %>
        <%= f.file_field :picture, class: 'form-control' %><br>

        <%= f.submit 'Ajouter', class: 'form-control' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/recipes/show.html.erb
<%= link_to 'Back', :back %>

<div class='container text-center'>
  <h1 class='text-center'><%= @recipe.name %></h1>  

    <%= image_tag @recipe.picture.url(:medium) %>
    <p>Quantity: <%= @recipe.quantity %></p>
    
    <h2>Produits</h2>
    <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <th scope="row"><%= link_to product.id, admin_product_path(product) %></th>
          <td><%= link_to product.name, admin_product_path(product) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>  


</div>

</div>