config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'

  post    :login,  to: 'sessions#create'
  delete  :logout, to: 'sessions#destroy'

  get :my_account, to: 'pages#my_account', path: 'mon-compte'
  get :finalize,   to: 'carts#finalize', path: 'finaliser-ma-commande'
  put :checkout,   to: 'carts#checkout', path: 'checkout-ma-commande'

  resources :users do
    resources :addresses, controller: 'users/addresses'
    resources :orders,    controller: 'users/orders'
  end

  resources :orders
  resources :products,  only: [:index, :show]
  resources :carts,     only: [:show, :create] do 
    resources :products, only: [:destroy]
  end

  resources :password_resets, only: [:new, :create, :edit, :update] do
  	collection do
  		get :success
  	end
  end

  namespace :admin do
    get :dashboard, to: 'admin#dashboard'
    resources :users
    resources :products
    resources :recipes
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  end

  def create
    cart_service = CartService.new(order: current_order, user: current_user, params: params)
    if cart_service.add_to_cart
      flash[:success] = "Ajouté au panier"
      redirect_back fallback_location: root_path
    else
      flash[:danger] = "Non ajouté au panier"
      redirect_back fallback_location: root_path
    end
  end

  def finalize
    current_order
  end

  def checkout
    cart_service = CartService.new(order: current_order, user: current_user, params: order_params)
    if cart_service.checkout
      flash[:success] = "Panier checkouté"
      cookies.delete :order_id
      redirect_to root_path
    else
      render :finalize
    end
  end

  private
  def current_order
    if cookies.permanent[:order_id]
      @current_order ||= Order.find(cookies.permanent[:order_id]) if cookies.permanent[:order_id]
    else
      @current_order ||= Order.create
      cookies.permanent[:order_id] = @current_order.id
      @current_order
    end
  end

  def order_params
    params.require(:order).permit!
  end
end

app/helpers/cart_helper.rb
module CartHelper
  def cart_delivery_title
    current_order.free_delivery? ? 'LIVRAISON GRATUITE ACTIVÉ' : 'Livraison gratuite à partir de 35€ d\'achat.'
  end
end

app/views/carts/_form.html.erb
<%= form_for current_order, url: checkout_path, method: :put do |f| %>
  
  <%= f.fields_for :addresses, current_order.addresses.build do |address_form| %>
    <div id='billing_address'>
      <h2>Details de facturation</h2>
      <div class="row">
        <div class="col-xs-6">
          <%= address_form.label :first_name, 'Prenom' %>
          <%= address_form.text_field :first_name, value: current_user&.first_name, class: 'form-control' %>
        </div>
        <div class="col-xs-6">
          <%= address_form.label :last_name, 'Nom' %>
          <%= address_form.text_field :last_name, value: current_user&.last_name, class: 'form-control' %>
        </div>
      </div>

      <%= address_form.label :entreprise_name, 'Nom de l\'entreprise' %>
      <%= address_form.text_field :entreprise_name, value: current_user&.billing_address.entreprise_name, class: 'form-control' %>

      <%= address_form.label :country, 'Pays' %>
      <%= address_form.text_field :country, value: current_user&.billing_address.country, class: 'form-control', disabled: true %>

      <%= address_form.label :street_name, 'Adresse' %>
      <%= address_form.text_field :street_name, value: current_user&.billing_address.street_name, class: 'form-control' %><br>
      <%= address_form.text_field :street_name_2, value: current_user&.billing_address.street_name_2, class: 'form-control' %>
      <%= address_form.label :city, 'Ville' %>
      <%= address_form.text_field :city, value: current_user&.billing_address.city, class: 'form-control' %>
      <%= address_form.label :postal_code, 'Code postal' %>
      <%= address_form.phone_field :postal_code, value: current_user&.billing_address.postal_code, class: 'form-control' %>

      <div class="row">
        <div class="col-xs-6">
          <%= address_form.label :phone, 'Telephone' %>
          <%= address_form.phone_field :phone, value: current_user&.billing_address.phone, class: 'form-control' %>
        </div>
        <div class="col-xs-6">
          <%= address_form.label :email, 'Adresse email' %>
          <%= address_form.email_field :email, value: current_user&.billing_address.email, class: 'form-control' %>
        </div>
      </div>
      <br>
    </div>
    
    <%= address_form.label :same_as_delivery, 'Meme adresse de livraison ?' %>
    <%= address_form.check_box :same_as_delivery, checked: true %>


    <div id='delivery_address'>
      <h2>Details de livraison</h2>
      <div class="row">
        <div class="col-xs-6">
          <%= address_form.label :first_name, 'Prenom' %>
          <%= address_form.text_field :first_name, value: current_user&.first_name, class: 'form-control' %>
        </div>
        <div class="col-xs-6">
          <%= address_form.label :last_name, 'Nom' %>
          <%= address_form.text_field :last_name, value: current_user&.last_name, class: 'form-control' %>
        </div>
      </div>

      <%= address_form.hidden_field :category, value: 'delivery' %>

      <%= address_form.label :entreprise_name, 'Nom de l\'entreprise' %>
      <%= address_form.text_field :entreprise_name, value: current_user&.billing_address.entreprise_name, class: 'form-control' %>

      <%= address_form.label :country, 'Pays' %>
      <%= address_form.text_field :country, value: current_user&.billing_address.country, class: 'form-control', disabled: true %>

      <%= address_form.label :street_name, 'Adresse' %>
      <%= address_form.text_field :street_name, value: current_user&.billing_address.street_name, class: 'form-control' %><br>
      <%= address_form.text_field :street_name_2, value: current_user&.billing_address.street_name_2, class: 'form-control' %>
      <%= address_form.label :city, 'Ville' %>
      <%= address_form.text_field :city, value: current_user&.billing_address.city, class: 'form-control' %>
      <%= address_form.label :postal_code, 'Code postal' %>
      <%= address_form.phone_field :postal_code, value: current_user&.billing_address.postal_code, class: 'form-control' %>

      <div class="row">
        <div class="col-xs-6">
          <%= address_form.label :phone, 'Telephone' %>
          <%= address_form.phone_field :phone, value: current_user&.billing_address.phone, class: 'form-control' %>
        </div>
        <div class="col-xs-6">
          <%= address_form.label :email, 'Adresse email' %>
          <%= address_form.email_field :email, value: current_user&.billing_address.email, class: 'form-control' %>
        </div>
      </div>
      <br>
    </div>

  <% end %>
  <%= f.submit 'Sauvegarder l\'Adresse', class: 'form-control', id: 'save_address_submit' %>
<% end %>

<script type="text/javascript">
  if($('#order_addresses_attributes_0_same_as_delivery:checkbox:checked').length > 0){
    $('#delivery_address').hide();  
  }else{
    $('#delivery_address').show();  
  }

  $('#order_addresses_attributes_0_same_as_delivery').change(function(){
    if(this.checked){
      $('#delivery_address').hide('slow');
    }else{
      $('#delivery_address').show('slow');
    }
  })

  $('#save_address_submit').click(function(e){
    if($('#order_addresses_attributes_0_same_as_delivery:checkbox:checked').length > 0){
      $('#delivery_address').remove();  
    }
  });
</script>

app/views/carts/finalize.html.erb
<div class='container'>
  <h1 class='text-center'>Finaliser ma commande</h1>

  <div class="row">
    <div class="col-md-6">
      <%= render 'form' %>
    </div>

    <div class="col-md-6">
      <h2>Votre commande</h2>
      <div class='jumbotron'>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">PRODUIT</th>
              <th scope="col">TOTAL</th>
            </tr>
          </thead>
          <tbody>
            <% current_order.order_items.each do |item| %>
              <tr>
                <td><%= "#{item.product.name}x#{item.quantity}" %></td>
                <td><%= item.total_price %>€</td>
              </tr>
              <tr>
                <td>SOUS-TOTAL</td>
                <td><%= current_order.total_item_price %>€</td>
              </tr>
              <tr>
                <td>EXPÉDITION</td>
                <td><%= current_order.delivery_cost %>€</td>
              </tr>
              <tr>
                <td>TOTAL</td>
                <td><%= current_order.total_price %>€ (inclut <%= current_order.tva %>€ TVA)</td>
              </tr>
            <% end %>
          </tbody>
        </table> 
      </div>
    </div>
  </div>
</div>

app/views/carts/show.html.erb
<div class='container'>
  <h1 class='text-center'>Panier</h1>

  <h2><%= cart_delivery_title %></h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col">Produit</th>
        <th scope="col">Prix</th>
        <th scope="col">Quantite</th>
        <th scope="col">Total</th>
      </tr>
    </thead>
    <tbody>
      <% current_order.order_items.each do |item| %>
        <tr>
          <td><%= link_to 'x', cart_product_path(current_order, item.product), method: :delete %></td>
          <td><%= image_tag item.product.recipes.first.picture.url(:thumb) %></td>
          <td><%= link_to item.product.name, product_path(item.product) %></td>
          <td><%= item.unit_price %></td>
          <td><%= item.quantity %></td>
          <td><%= item.total_price %></td>
        </tr>
      <% end %>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Livraison TNT: <%= current_order.delivery_cost %></td>
        <td>TOTAL: <%= current_order.total_price %></td>  
      </tr>
    </tbody>
  </table> 

  <%= link_to 'Proceder a la commande', finalize_path, class: 'btn btn-success right' %> 
</div>