config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'

  post    :login,  to: 'sessions#create'
  delete  :logout, to: 'sessions#destroy'

  get :my_account, to: 'pages#my_account', path: 'mon-compte'
  get :finalize,   to: 'carts#finalize', path: 'finaliser-ma-commande'
  put :checkout,   to: 'carts#checkout', path: 'checkout-ma-commande'

  resources :users do
    resources :addresses, controller: 'users/addresses'
    resources :orders,    controller: 'users/orders'
  end

  resources :orders
  resources :products,  only: [:index, :show]
  resources :carts,     only: [:show, :create] do 
    resources :products, only: [:destroy]
  end

  resources :password_resets, only: [:new, :create, :edit, :update] do
  	collection do
  		get :success
  	end
  end

  namespace :admin do
    get :dashboard, to: 'admin#dashboard'
    resources :users
    resources :products
    resources :recipes
  end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  price       :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ApplicationRecord
  # Associations
  has_many :recipezations, dependent: :destroy
  has_many :recipes, through: :recipezations
  has_many :order_items

  accepts_nested_attributes_for :recipezations, :recipes

  # Validations
  validates_presence_of :name, :description, :price
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < AdminController
    before_action :find_product, only: [:show, :edit, :update]

    def index
      @products = Product.all
    end

    def show
      @recipes = @product.recipes
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        flash[:success] = 'Produit ajouté'
        redirect_to admin_products_path
      else
        flash.now[:danger] = 'Produit non ajouté'
        render :new
      end
    end

    def edit
      @recipezations = @product.recipezations
    end

    def update
      if @product.update(product_params)
        flash[:success] = 'Produit modifié'
        redirect_to admin_products_path
      else
        flash.now[:danger] = 'Produit non modifié'
        render :edit
      end
    end

    private
    def product_params
      params.require(:product).permit(:name, :description, :price, recipezations_attributes: [:id, :quantity, :recipe_id, :_destroy])
    end

    def find_product
      @product = Product.find(params[:id])
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = Product.joins(:recipes).uniq
  end

  def show
    @product = Product.find(params[:id])
    @recipes = @product.recipes
  end

  def destroy
    current_order.order_items.find_by(product_id: params[:id]).destroy

    flash[:success] = "Produit retiré"
    redirect_to cart_path(current_order)
  end
end

app/views/admin/products/_recipezation_fields.html.erb
<div class='nested-fields'>
  <div class='field'>
    <%= f.label :name %>
    <%= f.collection_select :recipe_id, Recipe.all, :id, :name, {prompt: true}, class: 'form-control' %>
  </div>

  <br>

  <div class='field'>
    <%= f.label :quantity %>
    <%= f.number_field :quantity, class: 'form-control' %>    
  </div>
  <%= link_to_remove_association 'Remove recipe', f %>
</div>

app/views/admin/products/edit.html.erb
<div class='container'>
  <h1 class='text-center'>Edit <%= @product.name %></h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @product, url: admin_product_path(@product), method: :put, html: { multipart: true } do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %><br>

        <%= f.label :price %>
        <%= f.number_field :price, min: 0, class: 'form-control' %><br>

        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %><br>

        <h2>Recettes</h2>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Nom</th>
              <th scope="col">Quantite</th>
            </tr>
          </thead>
          <tbody>
            <%= f.fields_for :recipezations do |recipezation_form| %>
              <tr>
                <td><%= recipezation_form.object.recipe.name %></td>
                <td><%= recipezation_form.number_field :quantity, value: recipezation_form.object.quantity %></td>
              </tr>
            <% end %>
          </tbody>
        </table>  
        <%= f.submit 'Modifier', class: 'form-control' %> 
      <% end %>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class='container'>
  <h1 class='text-center'>Products#index</h1>

  <%= link_to 'Ajouter des produits', new_admin_product_path %>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Price</th>
        <th scope="col">Recipes</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <th scope="row"><%= product.id %></th>
          <td><%= link_to product.name, admin_product_path(product) %></td>
          <td><%= product.description %></td>
          <td><%= product.price %></td>
          <td><%= product.recipes.count %></td>
          <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>  
</div>

app/views/admin/products/new.html.erb
<div class='container'>
  <h1 class='text-center'>Product#new</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @product, url: admin_products_path, html: { multipart: true } do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %><br>

        <%= f.label :price %>
        <%= f.number_field :price, min: 0, class: 'form-control' %><br>

        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %><br>

        <%= f.fields_for :recipezations, @product.recipezations.build do |recipezation_form| %>
          <%= render 'recipezation_fields', f: recipezation_form %>
        <% end %>

        <div class='links'>
          <%= link_to_add_association 'Add recipe', f, :recipezations %>
        </div>

        <%= f.submit 'Ajouter', class: 'form-control' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<%= link_to 'Back', :back %>

<div class='container'>
  <h1 class='text-center'><%= @product.name %></h1>  

    <h2>Description</h2>
    <p><%= @product.description %></p>

    <h2>Recettes</h2>
    <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Image</th>
      </tr>
    </thead>
    <tbody>
      <% @recipes.each do |recipe| %>
        <tr>
          <th scope="row"><%= link_to recipe.id, admin_recipe_path(recipe) %></th>
          <td><%= link_to recipe.name, admin_recipe_path(recipe) %></td>
          <td><%= image_tag recipe.picture.url(:thumb) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>  
</div>

</div>