config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'

  post    :login,  to: 'sessions#create'
  delete  :logout, to: 'sessions#destroy'

  get :my_account, to: 'pages#my_account', path: 'mon-compte'
  get :finalize,   to: 'carts#finalize', path: 'finaliser-ma-commande'
  put :checkout,   to: 'carts#checkout', path: 'checkout-ma-commande'

  resources :users do
    resources :addresses, controller: 'users/addresses'
    resources :orders,    controller: 'users/orders'
  end

  resources :orders
  resources :products,  only: [:index, :show]
  resources :carts,     only: [:show, :create] do 
    resources :products, only: [:destroy]
  end

  resources :password_resets, only: [:new, :create, :edit, :update] do
  	collection do
  		get :success
  	end
  end

  namespace :admin do
    get :dashboard, to: 'admin#dashboard'
    resources :users
    resources :products
    resources :recipes
  end
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container text-center">
    <%= link_to 'Nos produits', products_path %>
    <%= link_to 'Melangez', '#' %>
    <%= link_to 'Evenements', '#' %>
    <%= link_to 'Journal', '#' %>
    <% if current_user %>
      <%= link_to 'Mon compte', user_path(current_user) %>
      <%= link_to 'Admin', admin_dashboard_path %>
    <% else %>
      <%= link_to 'Login', my_account_path %>
    <% end %>
    <% if current_order %>
      <%= link_to "Panier(#{current_order.order_items.count})", cart_path(current_order) %>
    <% else %>
      Panier (0)
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dear Muesli</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flashes' %>
    <div class="container">
      <%= yield %>  
    </div>
  </body>
</html>